# Generated by Django 2.2.6 on 2023-04-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hacks',
            name='pwn_count',
            field=models.PositiveIntegerField(),
        ),
    ]
